name = "storyweaver-backend"
main = "src/index.ts"
compatibility_date = "2025-07-18"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "storyweaver-jwt-secret-key-2024-secure"
SUPABASE_URL = "https://dqmwpihbwggsjwmpktmo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxbXdwaWhid2dnc2p3bXBrdG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3ODg1MzAsImV4cCI6MjA4MzM2NDUzMH0.Xv6yLeJym9EaorbRfnrZ2d8uC7kkN57aacFJvy9O9jA"

[[kv_namespaces]]
binding = "STORYWEAVER_KV"
id = "25a1eb2c26e645b59f1eab2e33dcdb5c"